# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tuna < Formula
  desc "Software to generate and serve JSON/HTML with flow model"
  homepage "https://github.com/solaoi/tuna-mayonnaise"
  version "0.2.0-alpha"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/solaoi/tuna-mayonnaise/releases/download/v0.2.0-alpha/tuna_0.2.0-alpha_macOS-64bit.tar.gz"
      sha256 "0bcc4efd5ec16e6517f6974c687b79dedaceff4992a7c3f1833e4b8fefbdc75a"
    end
    if Hardware::CPU.arm?
      url "https://github.com/solaoi/tuna-mayonnaise/releases/download/v0.2.0-alpha/tuna_0.2.0-alpha_macOS-ARM64.tar.gz"
      sha256 "04a257def50fae4d71b6486303a065381b63168c3f8c6466f0f83225eb22afcf"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/solaoi/tuna-mayonnaise/releases/download/v0.2.0-alpha/tuna_0.2.0-alpha_Linux-64bit.tar.gz"
      sha256 "3d539d0847eac405897fb8de7a34098fe169bc5971f21bba4be30d8baffd8cbd"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/solaoi/tuna-mayonnaise/releases/download/v0.2.0-alpha/tuna_0.2.0-alpha_Linux-ARM64.tar.gz"
      sha256 "c23b28718e39be883ee3e4b11fd855b1c62b86d21bc3b60a9df0c90d281c6e54"
    end
  end

  def install
    bin.install "tuna"
  end

  test do
    system "#{bin}/tuna help"
  end
end
