# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tuna < Formula
  desc "Software to generate and serve JSON/HTML on the node-based editor"
  homepage "https://github.com/solaoi/tuna-mayonnaise"
  version "0.0.1"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/solaoi/tuna-mayonnaise/releases/download/v0.0.1/tuna_darwin_amd64.tar.gz"
      sha256 "b256db439ee6d768fbcfdc935ba60710e121be8fcd78f3c97ff73d06d08c31df"
    end
    if Hardware::CPU.arm?
      url "https://github.com/solaoi/tuna-mayonnaise/releases/download/v0.0.1/tuna_darwin_arm64.tar.gz"
      sha256 "a1fef2d3503c3b8d866c44257fdbf70b6418d1cb73bbac6ac220684874577d16"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/solaoi/tuna-mayonnaise/releases/download/v0.0.1/tuna_linux_amd64.tar.gz"
      sha256 "6f0432f3aa5f5d41f7a895d454712a4ec0f1f601dd9f2a0cac617fad9e47c035"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/solaoi/tuna-mayonnaise/releases/download/v0.0.1/tuna_linux_arm64.tar.gz"
      sha256 "ce3add07f7266840fd27a734f53ef4509fafe9e8cfcf117109261e5efbcfbd30"
    end
  end

  def install
    bin.install "tuna"
  end

  test do
    system "#{bin}/tuna help"
  end
end
